### ISSUE TITLE
可以随着原字体的更新而更新吗？

### ISSUE THREAD

**Issue by lxgw** [chawyehsu/lxgw-wenkai-webfont#1]
前几天更新了 [1.006 版](https://github.com/lxgw/LxgwWenKai/releases/tag/v1.006)，优化了一些字形。

**Comment by chawyehsu** [comment]
https://github.com/chawyehsu/lxgw-wenkai-webfont/commit/746fa26c758d9e2c4b172f03da696417c9cfa14a 更新了。因为是手工转换格式，会延迟没完全同时跟着上游一起更新。

**Comment by chawyehsu** [comment]
@lxgw 谢谢。我会抽时间更新下这个库。考虑到兼容性，我应该直接添加 Lite 版字体而不会覆盖。

制作字体辛苦了。

**Comment by hyrious** [comment]
可以试试用 GitHub Actions 跑更新

**Comment by chawyehsu** [comment]
已经重构完成，现在会定时自动检查更新和打包发版。Lite 和 TC 字体也分包制作完成了。

**Comment by cnyyk** [comment]
借用宝地发一个评论，当前 1.120 已发布，但 web-font 貌似没有同步更新，见：
https://github.com/lxgw/LxgwWenKai/releases/tag/v1.120

@chawyehsu

**Comment by chawyehsu** [comment]
@cnyyk 定时任务在每周一下午四点

**Comment by cnyyk** [comment]
哦，明白，谢谢。这样也算是比较低碳了。
