### ISSUE TITLE
缺字，可能是转换的问题

### ISSUE THREAD

**Issue by jhintr** [chawyehsu/lxgw-wenkai-webfont#16]
我稍作对比，下面这些在 ttf 中有而网页版无：

竪，縕，諐，槨，幃，儻，覿，悁，殫，颻，罇

不知是转换过程的问题还是版本的问题，谢谢！

PS: 发现问题在 `unicode.json` 里，这些字不在 subset 中，请问 `unicode.json` 是由何而来的？

**Comment by chawyehsu** [comment]
你好，谢谢反馈。大致查询了一下这几个字的 unicode 确实不在 `unicode.json` 中。

`unicode.json` 取自 Google 的 Noto Sans SC，具体为 https://github.com/fontsource/fontsource/blob/main/packages/noto-serif-sc/unicode.json。

你给出的这几个字应该是不属于 SC 的字集里面，所以被忽略了。对于这个问题，可能得重新安排 subset 才能解决，关于 `unicode.json` 的编排或者挑选，我没有什么想法，欢迎提出建议。

**Comment by jhintr** [comment]
感谢回复！我这几天写了 [unicode.py](https://github.com/jhintr/ttf2woff2/blob/master/unicode.py)，把基本区里缺的都补充到 [unicode_ex.json](https://github.com/jhintr/ttf2woff2/blob/master/unicode_ex.json) 这个文件里面了，但估计还有少数在扩展 A~F 区里面的，等看到了手动加吧。

从你这里抄到不少，不知是否合适，感谢！
