### ISSUE TITLE
国内CDN

### ISSUE THREAD

**Issue by cxw620** [chawyehsu/lxgw-wenkai-webfont#21]
建议在readme中说一下`npm.elemecdn.com`可作为国内用户的CDN源, 速度更快.
如 `https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css` -> `https://npm.elemecdn.com/lxgw-wenkai-webfont@1.1.0/style.css`

**Comment by MurphyZX** [comment]
试了下速度快了不少

**Comment by cxw620** [comment]
> `npm.elemecdn.com` 稳定吗？

是饿了么的, 似乎也稳定提供服务好几年了

**Comment by cxw620** [comment]
顺带提一句, 例如假设刚刚推了1.2.0版本, 访问`https://npm.elemecdn.com/lxgw-wenkai-webfont@1.2.0/style.css`大概率是提示Access Deny, 原因是还没有缓存, 等个15分钟就行

**Comment by cxw620** [comment]
这个方案寄了

**Comment by cxw620** [comment]
向cdnjs提了pr, merge了一个, 预计若干周后就能同步. 暂时只有`lxgw-wenkai-screen-webfont`, `lxgw-wenkai-webfont`等待合并. 
国内可用镜像: `https://mirrors.sustech.edu.cn/cdnjs/`

**Comment by cxw620** [comment]
热烈庆祝! 国内已经有镜像啦! 
https://cdn.staticfile.org/lxgw-wenkai-webfont/1.6.0/style.css
https://cdn.staticfile.org/lxgw-wenkai-screen-webfont/1.6.0/style.css

**Comment by chawyehsu** [comment]
Nice! 方便的话欢迎提个 PR 更新到 README

**Comment by cxw620** [comment]
> Nice! 方便的话欢迎提个 PR 更新到 README

https://github.com/chawyehsu/lxgw-wenkai-webfont/pull/24
