### ISSUE TITLE
BootCDN、Bootcss、Staticfile 供应链投毒已被uBlock Origin、Google Ads等屏蔽,建议移除

### ISSUE THREAD

**Issue by tjsky** [chawyehsu/lxgw-wenkai-webfont#32]
Polyfill.io，BootCDN、Bootcss、Staticfile 4家静态文件CDN已经被黑产收购并实控进行供应链投毒。
目前Google Ads、uBlock等已经对其做了屏蔽和警告处理。建议移除。

![_20240709145006](https://github.com/chawyehsu/lxgw-wenkai-webfont/assets/7272911/325addf7-3d14-4063-a0c2-039b9c4d76ec)
![image](https://github.com/chawyehsu/lxgw-wenkai-webfont/assets/7272911/d1847862-b47d-48c5-ab1b-48b9904bd37d)

来源
[github:cdn.staticfile.org blocked wrongly #24292](https://www.tjsky.net/goto/?url=https://github.com/uBlockOrigin/uAssets/issues/24292)
[Polyfill.io JavaScript supply chain attack impacts over 100K sites](https://www.tjsky.net/goto/?url=https://blog.zhheo.com/p/61e9.html)
[Polyfill.io, BootCDN, Bootcss, Staticfile attack traced to 1 operator](https://www.tjsky.net/goto/?url=https://www.bleepingcomputer.com/news/security/polyfillio-bootcdn-bootcss-staticfile-attack-traced-to-1-operator/)

**Comment by chawyehsu** [comment]
谢谢告知

**Comment by chawyehsu** [comment]
已移除 https://github.com/chawyehsu/lxgw-wenkai-webfont/commit/29da4802a1900032c1630ef8adf446ea647e4c5e
